version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Website Install
          command: npm run website:install
      - run:
          name: Website Build
          command: npm run website:build
      - run:
          name: Deploy Website
          command: npm run website:deploy

workflows:
  build_and_deploy:
    jobs:
      - build-and-deploy
