version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build-and-deploy-backend:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
            pip3 install awsebcli --upgrade --user
      - run:
          name: Install Backend.Dependencies
          command: npm run dashboard-backend:install
      - run:
          name: Run Backend Prettier
          command: npm run dashboard-backend:prettier
      - run:
          name: Run Backend Lint
          command: npm run dashboard-backend:lint
      - run:
          name: Run Backend Tests
          command: npm run dashboard-backend:test
      - run:
          name: Zip the Application
          command: zip -r application.zip server.js package.json database.js handlers/ models/
      - run:
          name: Upload to S3
          command: aws s3 cp application.zip s3://awstestbucketfordb/application.zip
      - run:
           name: Deploy Back-End
           command: npm run dashboard-backend:deploy

  build-and-deploy-dashboard:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Dashboard Install
          command: npm run dashboard:install
      - run:
          name: Run Dashboard Prettier
          command: npm run dashboard:prettier
      - run:
          name: Run Dashboard Lint
          command: npm run dashboard:lint
      - run:
          name: Dashboard Build
          command: npm run dashboard:build
      - run:
          name: Deploy Dashboard
          command: npm run dashboard:deploy

  build-and-deploy-website:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Website Install
          command: npm run website:install
      - run:
          name: Run Website Prettier
          command: npm run website:prettier
      - run:
          name: Run Website Lint
          command: npm run website:lint
      - run:
          name: Website Build
          command: npm run website:build
      - run:
          name: Deploy Website
          command: npm run website:deploy

workflows:
  build_and_deploy:
    jobs:
      - build-and-deploy-dashboard
      - build-and-deploy-website
      - build-and-deploy-backend
