version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build-and-deploy-dashboard:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Dashboard Install
          command: npm run dashboard:install
      - run:
          name: Dashboard Build
          command: npm run dashboard:build
      - run:
          name: Deploy Dashboard
          command: npm run dashboard:deploy

  build-and-deploy-website:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Website Install
          command: npm run website:install
      - run:
          name: Website Build
          command: npm run website:build
      - run:
          name: Deploy Website
          command: npm run website:deploy

workflows:
  build_and_deploy:
    jobs:
      - build-and-deploy-dashboard
      - build-and-deploy-website
